#!/usr/bin/env bash
#
# Sync oh-my-zsh plugin aliases into standalone zsh files.
#
# Shallow-clones oh-my-zsh, extracts git, docker, docker-compose, and macOS
# plugin content into self-contained .zsh files that can be sourced without
# the oh-my-zsh framework.
#
# Usage: ./scripts/sync-omz-aliases.sh
#
# The generated files are written to zsh/plugins/ in this repo and should
# be committed after running.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$SCRIPT_DIR/zsh/plugins"
REPO_URL="https://github.com/ohmyzsh/ohmyzsh.git"

mkdir -p "$OUT_DIR"

# Clone oh-my-zsh to a temp directory
tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

echo "Cloning oh-my-zsh (shallow)..."
git clone --depth=1 --quiet "$REPO_URL" "$tmpdir/ohmyzsh"
omz="$tmpdir/ohmyzsh"

commit_hash=$(git -C "$omz" rev-parse --short HEAD)
commit_date=$(git -C "$omz" log -1 --format=%ci | cut -d' ' -f1)

header() {
  local plugin="$1"
  cat <<EOF
# $plugin aliases/functions extracted from oh-my-zsh
# Source: $REPO_URL
# Commit: $commit_hash ($commit_date)
# Generated by: scripts/sync-omz-aliases.sh
# DO NOT EDIT MANUALLY — re-run the sync script to update.

EOF
}

# ---------------------------------------------------------------------------
# git.zsh
# ---------------------------------------------------------------------------
echo "Generating git.zsh..."
{
  header "Git"

  echo "# Helper: git wrapper (from lib/git.zsh)"
  # Extract __git_prompt_git
  sed -n '/^function __git_prompt_git()/,/^}/p' "$omz/lib/git.zsh"
  echo ""

  echo "# Helper: get current branch name (from lib/git.zsh)"
  # Extract git_current_branch
  sed -n '/^function git_current_branch()/,/^}/p' "$omz/lib/git.zsh"
  echo ""

  echo "# Git plugin (plugins/git/git.plugin.zsh)"
  cat "$omz/plugins/git/git.plugin.zsh"
} > "$OUT_DIR/git.zsh"

# ---------------------------------------------------------------------------
# docker.zsh
# ---------------------------------------------------------------------------
echo "Generating docker.zsh..."
{
  header "Docker"

  # Extract only the alias lines (before the completion/caching logic)
  sed -n '/^alias /p' "$omz/plugins/docker/docker.plugin.zsh"
} > "$OUT_DIR/docker.zsh"

# ---------------------------------------------------------------------------
# docker-compose.zsh
# ---------------------------------------------------------------------------
echo "Generating docker-compose.zsh..."
{
  header "Docker Compose"

  cat "$omz/plugins/docker-compose/docker-compose.plugin.zsh"
} > "$OUT_DIR/docker-compose.zsh"

# ---------------------------------------------------------------------------
# macos.zsh
# ---------------------------------------------------------------------------
echo "Generating macos.zsh..."
{
  header "macOS"

  # Extract the plugin, but:
  # - Skip the $0 handling lines (oh-my-zsh specific)
  # - Skip the comment above $0 handling
  # - Skip the music/spotify source lines and their comments at the end
  # - Replace open_command with open
  sed \
    -e '/^0="/d' \
    -e '/^# Handle \$0/d' \
    -e '/zdharma-continuum.*Zsh-Plugin-Standard/d' \
    -e '/^source "\${0:h:A}/d' \
    -e '/^# Music \/ iTunes control function/d' \
    -e '/^# Spotify control function/d' \
    -e 's/open_command/open/g' \
    "$omz/plugins/macos/macos.plugin.zsh"
} > "$OUT_DIR/macos.zsh"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "Generated files in $OUT_DIR:"
for f in "$OUT_DIR"/*.zsh; do
  lines=$(wc -l < "$f" | tr -d ' ')
  aliases=$(grep -c '^\s*alias ' "$f" || true)
  functions=$(grep -c '^\s*function ' "$f" || true)
  echo "  $(basename "$f"): $lines lines, $aliases aliases, $functions functions"
done
echo ""
echo "Upstream commit: $commit_hash ($commit_date)"
echo "Done. Review changes and commit."
